image_root: '/graphics/scratch2/staff/Hassan/checkpoints/lyrics_to_prompts/temp/haivmet'
dataset: 'haivmet'

# set pretrained as a file path or an url
pretrained: '/graphics/scratch2/students/ghoshadh/SongAnimator/models/retrieval/model_base_retrieval_coco.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 32
batch_size_test: 64
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

image_size: 400
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6